### ISSUE TITLE
how to deal with biological replicate

### ISSUE THREAD

**Issue by biozzq** [vaquerizaslab/chess#31]
Dear all,

If we have biological data, how to run `chess sim`? Thank you very much.

Best wishes,
Zheng zhuqing

**Comment by liz-is** [comment]
Hello,

I'm not a CHESS developer but have used it in a few projects in the Vaquerizas Lab. There isn't a straightforward answer to your question, in my opinion, because it depends on your data and your aims. 

1. One option is to run `chess sim` on biological replicates independently, and then select regions of interest which are significant (pass your ssim / SN thresholds) in multiple replicates - similarly to how you might call peaks on individual ChIP-seq replicates and then keep overlapping peaks. 

2. Alternatively, if your biological replicates are very similar to each other, you may be able to merge them and reach a higher resolution of the Hi-C matrix, which might give better results. 

3. A third option would be to compare (control) biological replicates against each other to get a "reference" track that gives you some idea of how much the ssim varies genome-wide between samples that should be very similar, due to noise and the general properties of different genomic regions. (I have tried out this approach in the past but ultimately went with option 2 above for that project.) This is along the same lines as the WT/ctrl comparison in Fig 4 of the CHESS paper. Along with SN filtering, this can help identify regions where reduced ssim is due to biological factors rather than technical factors / noise. 

In my experience I've usually gone for option 2 above, because resolution is usually the limiting factor for my CHESS analyses and my Hi-C replicates are usually very similar. You can always run individual replicates and check the correlation of their ssim scores, first.

**Comment by biozzq** [comment]
Dear @liz-is 

Thank you for your detailed information. Yes, i will do according to you. As you have used `chess` in your project, i am wondering that how do you process your HiC data before using `chess`, I usually use `HiC-Pro` to generate validpairs file, then use `fanc` to convert the validpairs to hic file and do balance. However, I found that it will take a long time to run `fanc`. Do you have any other suggestion?

Best wishes,
Zheng zhuqing

**Comment by liz-is** [comment]
I use FAN-C for the whole process from reads to normalised matrices. I find that the alignment step usually takes the longest, although matrix normalisation can take a long time at high resolution (<5 kb). Having said that I mainly work with Drosophila data so the genome is pretty small.

**Comment by biozzq** [comment]
Thank you very much and looking forward to the updated FAN-C.
