### ISSUE TITLE
CNV bias in normalization

### ISSUE THREAD

**Issue by jazberna1** [vaquerizaslab/chess#44]
Hello CHESS team,

This is not a issue. I wanted to ask you if the Obs/Exp normalization in CHESS somehow corrects CNV bias or if this something not needed to take into account.

Many thanks
Jorge

**Comment by liz-is** [comment]
Hi Jorge,

Bias due to CNVs is typically accounted for during the matrix balancing step of producing Hi-C matrices. CHESS takes balanced matrices as input, as stated in the documentation. Depending on the nature of the CNV, there may be changes in the Hi-C matrix that aren't removed by matrix balancing, but over/under-representation of a region that varies in copy number should be accounted for already.

**Comment by jazberna1** [comment]
Hello Liz,

Thanks so much for the clarification!

Regards
Jorge
