### ISSUE TITLE
NaN continued

### ISSUE THREAD

**Issue by cgirardot** [vaquerizaslab/chess#9]
Dear chess team, 
I have similar results as described in #5 . 

I can directly rule out the `chr` naming issue as I successfully ran chess sim on the same matrices but with larger win size ie : 
- win=500Kb ; step=100Kb => works
- win=250Kb ; step=50Kb => works
- win=100Kb ; step=20Kb => only NaN
- win=50Kb ; step=25Kb => only NaN

My genome is dm6, I am using an ICEd matrix with 10K bins (I should not have much NA bins).  
Is this expected?

**Comment by nickmachnik** [comment]
Hi cgirardot. I am quite sure that the issue here is that the window size is too small.  I just realized that the docs do not contain any information about that, I think it got lost when moving to readthedocs, sorry about that!

The program doesn't accept window sizes that are below 20x your bin size. In your case, 200 kb windows is the smallest that will work. The reasoning here is that too small windows will contain enough features to allow for meaningful comparisons. In the paper's methods we recommend a minimal window size of 100x the bin size.

This needs to be re added to the docs. Also, it would be good to abort the `chess sim` run immediately when the window size is too small, and give an explicit error.

**Comment by nickmachnik** [comment]
I added info about this to the docs. From 0.3.5 on we now also check whether the minimum region size requirement is met globally before running any comparisons, and exit with an explicit error. 

I will close, as this seems resolved.
